### ISSUE TITLE
Add local install instructions to README, update OPAM version

### ISSUE THREAD

**Issue by aupiff** [pirapira/bamboo#206]
I'm not familiar with the OCaml ecosystem but I am interested in developing `bamboo` locally. When I followed the README's instructions to `opam install bamboo`, the outdated version of `bamboo` gave me trouble since it `uint` has been renamed `uint256` and many of the example contracts were not compiling.

I'd suggesting adding instructions for doing local builds by adding a opam bin to one's local bamboo repo: `opam pin add bamboo .`; I will happily submit a PR with this updated in the docs, but I wanted to make sure that this follows OCaml best practices.

I'd also suggest bumping the version number and deploying this new version to the OPAM repository.

**Comment by pirapira** [comment]
Thank you.  These are good suggestions.  I'll take care of these.

**Comment by aupiff** [comment]
This has been taken care of.
