### ISSUE TITLE
024_vault example throws invalid JUMP

### ISSUE THREAD

**Issue by timgestson** [pirapira/bamboo#248]
When attempting to unvault, this error is thrown:
```
Unhandled rejection Error: VM Exception while processing transaction: invalid JUMP at 22602468ebe59af1c98d7bf3a52002352feb272cc4ee3ba9c302817595247ec0/1f1a77513c238d23f95b003347de7f554c6f177f:1368
```
steps to reproduce:
- create vault
- send vault money
- try to unvault

as seen here:
https://github.com/timgestson/bamboo-tests/blob/cbcc36bcdc01ea1c966bb59f21ab071dc3caf7a7/test/vault.js#L30

**Comment by pirapira** [comment]
I was able to reproduce the problem.

**Comment by pirapira** [comment]
I was able to get the debug trace with this: https://github.com/pirapira/bamboo-tests/tree/debug-unvault

And the `unvault` trace propertly finishes with a `STOP`.  So I'm confused.

**Comment by pirapira** [comment]
This has been fixed.  The issue was caused by this line https://github.com/pirapira/bamboo-tests/compare/e1e95a6477203f86244731201c79147a15cb7ed8...b5241452adbdb65898674523bed7ff7f40bdebf3#diff-cc0be17fd34cc93e5da4260b5a33ec34R23
