### ISSUE TITLE
Incorrect characters when compiling 01b_erc20better.bbo

### ISSUE THREAD

**Issue by jrainville** [pirapira/bamboo#279]
When running `bamboo --abi < src/parse/examples/01b_erc20better.bbo`, the result was not correct JSON, as there was `uint256` in the generated ABI before the opening bracket.
Here is a screenshot:
![bambooabierror](https://user-images.githubusercontent.com/11926403/38874545-579a738e-4226-11e8-91ab-8a2bb0fee799.png)

I tried with 006auction_first_case.bbo before and it does work.

**Comment by pirapira** [comment]
I'll proceed like this:

* [ ] reproduce the problem
* [ ] add the bug in a test case in Travis runs
* [ ] fix the problem

**Comment by pirapira** [comment]
The problem doesn't exist on `master` so I need to make a new release.

**Comment by pirapira** [comment]
A new release depends on #281.

**Comment by pirapira** [comment]
@jrainville please try `opam update; opam upgrade`. That fixes this problem for me.

**Comment by jrainville** [comment]
Yup it worked! Thank you! :)
