### ISSUE TITLE
implement decimal numeric literal

### ISSUE THREAD

**Issue by pirapira** [pirapira/bamboo#90]

**Comment by aupiff** [comment]
I've started on this in #208. It seems like a good way for me to familiarize myself with the code base.

**Comment by pirapira** [comment]
Thank you. The codebase is sometimes messy. Any improvements are welcome!

**Comment by pirapira** [comment]
So far the pull-request looks good.  You will need to determine the type of a decimal literal as you have noticed.  It gets sometimes hairly when literals are combined with operators, like `1 + 2 + 3 * 999`.  Then somehow the contextual information needs to be passed along.

Maybe it's easier to introduce literals indicating types, like `100u8` and `100u256`

**Comment by aupiff** [comment]
Yes, it would be much easier to introduce literals with those endings. I'll do that for now and we can discuss changes to type inference in the future.

**Comment by aupiff** [comment]
I've added two new expression types, `DecLit8Exp` and `DecLit256Exp`. Any ordinary-looking decimal literal is assumed to be `uint256` but to write a `uint8` literal one must add a `u8` suffix as in `5u8`.
